#!/usr/bin/env bash
# vale-self-narration.sh — the estate's self-narration prose gate.
#
# Runs Vale with the shared Estate.SelfNarration rule (+ its provenance sibling)
# over the markdown pre-commit passes as args. Bans an artifact body narrating its
# own provenance/authorship ("Generated by Claude", "🤖 Generated", "Co-Authored-By:
# Claude", "(generated by Claude)") — authorship belongs in git history / Linear /
# PR metadata, not the doc body. The enforced subset of the retired qa.py's
# self-narration scan (slice 2b).
#
# Config resolution: the shared .vale.ini lives at dotty's root (one level up from
# git-hooks/); Vale resolves StylesPath relative to the --config file's own dir, so
# pointing --config there works from any cwd, including pre-commit's isolated cache
# clone of dotty (which carries .vale.ini + styles/ alongside this script).
#
# LOCAL FAIL-OPEN, CI-AUTHORITATIVE: if the vale binary is absent, this hook emits
# a one-time advisory and exits 0 — a rarely-firing style check does not earn a
# require-vale-on-every-machine install (unlike gitleaks, which is fail-closed
# security). Enforcement lives at the required CI check, where setup-vale installs
# the pinned binary so the rule really runs. When vale IS present, its exit code is
# passed through (1 = a self-narration hit blocks; a real Vale/config error also
# blocks — fail-closed once the engine is in play).
#
# Spec: {workspace_root}/System/Knowledge/corpus-conformance-methodology.md
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG="$HERE/../.vale.ini"

if ! command -v vale >/dev/null 2>&1; then
    echo "vale-self-narration: vale not installed — skipping locally (fail-open)." >&2
    echo "  The required CI check enforces this rule; install vale for local feedback: https://vale.sh/docs/install" >&2
    exit 0
fi

if [[ ! -f "$CONFIG" ]]; then
    echo "vale-self-narration: BLOCKED — shared Vale config not found at $CONFIG" >&2
    echo "  (expected dotty's .vale.ini one level above this hook; refusing to skip a check we cannot run)." >&2
    exit 2
fi

# pre-commit appends the markdown files as args. No files = nothing to scan.
[[ "$#" -gt 0 ]] || exit 0

# Vale's own alert log goes to stdout; replay everything so pre-commit shows it on
# failure. Exit code is Vale's own (0 clean; non-zero = alerts >= MinAlertLevel,
# i.e. an error-level self-narration hit, or a real execution error — both block).
vale --config "$CONFIG" "$@"
