#!/usr/bin/env bash
# Prepare native checks after entering a clone or worktree. Never runs the suite.
set -euo pipefail

fail() {
	echo "prepare-checkout: $*" >&2
	exit 1
}
[[ $# -le 1 ]] || fail "usage: prepare-checkout.sh [checkout]"
dotty=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
checkout=$(git -C "${1:-.}" rev-parse --show-toplevel) || fail "not a Git checkout"
cd "$checkout"
[[ -f .pre-commit-config.yaml ]] || fail "missing .pre-commit-config.yaml in $checkout"
for tool in pre-commit python3; do
	command -v "$tool" >/dev/null || fail "install $tool before preparing this checkout"
done
pre-commit validate-config .pre-commit-config.yaml

# Native pre-commit refuses core.hooksPath. Preserve it, including an empty
# setting; an existing owner needs an explicit, exercised integration.
if git config --get core.hooksPath >/dev/null; then
	fail "core.hooksPath is configured; preserve that owner and integrate its hooks before authoring"
fi
hooks_dir=$(git rev-parse --git-path hooks)
[[ ! -L "$hooks_dir" ]] || fail "custom symlinked hook directory at $hooks_dir; integrate its owner explicitly"
for hook in pre-commit commit-msg pre-push; do
	path=$(git rev-parse --git-path "hooks/$hook")
	[[ "$path" == /* ]] || path="$checkout/$path"
	[[ ! -L "$path" && ! -d "$path" ]] || fail "custom owner at $path; integrate it explicitly"
	if [[ -f "$path" ]] && ! grep -q '^# File generated by pre-commit:' "$path"; then
		[[ ! -e "$path.legacy" && ! -L "$path.legacy" ]] || fail "existing hook and legacy backup at $path; refusing to overwrite either"
		# The native installer preserves ordinary hooks as .legacy and invokes
		# them. A different pre-commit wrapper could run the suite twice.
		if grep -q 'pre-commit' "$path"; then
			fail "nonstandard pre-commit wrapper at $path; integrate its owner before installation"
		fi
	fi
done

# Read native declarations; remote hook environments are pre-commit's job.
# PyYAML is the same parser used by pre-commit, not a new config format.
tools=$(
	python3 - "$dotty" <<'PY'
import shlex
import subprocess
import sys
try:
    import yaml
except ImportError:
    sys.exit('prepare-checkout: python3 needs PyYAML to read native hook declarations')
with open('.pre-commit-config.yaml', encoding='utf-8') as stream:
    config = yaml.safe_load(stream)
needed = set()
# Existing project entrypoints wrap these tools. Keep their explicit
# prerequisites here; setup checks availability and never runs suites.
project_tools = {
    'dotty-hook-tests': {'jq', 'gitleaks', 'vale', 'actionlint', 'shellcheck', 'zizmor', 'node', 'npx'},
    'dotty-workflow-tests': {'jq'},
    'dotty-release-tests': {'jq'},
    'agent-ops-studio-project': {'node', 'npm'},
    'studio-project': {'node', 'npm'},
    'core-linear-tests': {'uvx'},
    'core-estate-hook-tests': {'jq', 'gitleaks'},
    'core-plugin-validation': {'claude'},
    'plugin-validation': {'claude'},
    'margot-route-contract': {'jq'},
    'margot-workflow-policy': {'conftest'},
    'core-standalone-check': {'jq', 'gitleaks'},
}
for repo in config['repos']:
    for hook in repo['hooks']:
        name = hook['id']
        if name == 'check-file-presence':
            subprocess.run(['bash', sys.argv[1] + '/git-hooks/check-file-presence.sh', '--setup',
                            *hook.get('args', [])], check=True, stdout=sys.stderr)
        if name.startswith('gitleaks-'):
            needed.add('gitleaks')
        if name == 'vale-self-narration':
            needed.add('vale')
        if name in {'actionlint', 'zizmor'}:
            needed.add(name)
        if name == 'actionlint':
            needed.add('shellcheck')
        needed.update(project_tools.get(name, set()))
        if repo['repo'] == 'local' and hook.get('language') == 'system':
            command = shlex.split(hook['entry'])
            if command:
                needed.add(command[0])
print('\n'.join(sorted(needed)))
PY
)

# shellcheck source=../.github/actions/setup-vale/release.sh
source "$dotty/.github/actions/setup-vale/release.sh"

# Vale is a system binary used by the script-language hook. Install only if
# declared and absent, using the existing approved release and pinned hashes.
if grep -qx vale <<<"$tools" && ! command -v vale >/dev/null; then
	case ":$PATH:" in
	*":$HOME/.local/bin:"*) ;;
	*) fail "add $HOME/.local/bin to this session's PATH before installing Vale" ;;
	esac
	case "$(uname -s)/$(uname -m)" in
	Darwin/arm64)
		platform=macOS_arm64
		;;
	Darwin/x86_64)
		platform=macOS_64-bit
		;;
	Linux/aarch64 | Linux/arm64)
		platform=Linux_arm64
		;;
	Linux/x86_64)
		platform=Linux_64-bit
		;;
	*) fail "install Vale $VALE_RELEASE_VERSION for this unsupported platform before preparing the checkout" ;;
	esac
	checksum=$(vale_release_checksum "$VALE_RELEASE_VERSION" "$platform") || fail "no reviewed Vale release for $platform"
	tmp=$(mktemp -d)
	trap 'rm -rf "$tmp"' EXIT
	curl -fsSL "https://github.com/errata-ai/vale/releases/download/v${VALE_RELEASE_VERSION}/vale_${VALE_RELEASE_VERSION}_${platform}.tar.gz" -o "$tmp/vale.tgz"
	python3 - "$tmp/vale.tgz" "$checksum" <<'PY'
import hashlib
import pathlib
import sys
if hashlib.sha256(pathlib.Path(sys.argv[1]).read_bytes()).hexdigest() != sys.argv[2]:
    sys.exit('prepare-checkout: Vale checksum mismatch; nothing installed')
PY
	tar -xzf "$tmp/vale.tgz" -C "$tmp" vale
	mkdir -p "$HOME/.local/bin"
	install -m 755 "$tmp/vale" "$HOME/.local/bin/vale"
fi
while IFS= read -r tool; do
	[[ -z "$tool" ]] && continue
	command -v "$tool" >/dev/null || fail "required tool missing: $tool (declared by .pre-commit-config.yaml)"
	case "$tool" in
	gitleaks) [[ "$(gitleaks version)" == '8.30.1' ]] || fail "gitleaks 8.30.1 is required by the approved baseline" ;;
	vale) [[ "$(vale --version)" == "vale version $VALE_RELEASE_VERSION" ]] || fail "Vale $VALE_RELEASE_VERSION is required by the approved baseline" ;;
	actionlint) [[ "$(actionlint -version | head -n 1)" == '1.7.12' ]] || fail "Actionlint 1.7.12 is required by the approved baseline" ;;
	zizmor) [[ "$(zizmor --version)" == 'zizmor 1.30.0' ]] || fail "Zizmor 1.30.0 is required by the approved baseline" ;;
	esac
done <<<"$tools"

pre-commit install --install-hooks --hook-type pre-commit --hook-type commit-msg --hook-type pre-push
for hook in pre-commit commit-msg pre-push; do
	path=$(git rev-parse --git-path "hooks/$hook")
	[[ "$path" == /* ]] || path="$checkout/$path"
	if [[ ! -x "$path" ]] || ! grep -q '^# File generated by pre-commit:' "$path"; then
		fail "native $hook hook not installed at $path"
	fi
done
printf 'prepare-checkout: ready: %s (pre-commit, commit-msg, pre-push)\n' "$checkout"
